### ISSUE TITLE
cannot stop slacker-cluster

### ISSUE THREAD

**Issue by mbuczko** [sunng87/slacker-cluster#19]
I'm not able to stop the cluster, following exception is thrown:
   
    boot.user=> (require '[slacker.server.cluster :as cluster])
    nil
    boot.user=> (def server (cluster/start-slacker-server '[my.own.api] 2014 :cluster {:name "my-cluster" :zk "127.0.0.1:2181"} :content-type :nippy))
    boot.user=> server
    [[[#object[io.netty.channel.nio.NioEventLoopGroup 0x247f34d3 "io.netty.channel.nio.NioEventLoopGroup@247f34d3"] #object[io.netty.channel.nio.NioEventLoopGroup 0x2bb764be "io.netty.channel.nio.NioEventLoopGroup@2bb764be"]] nil] #object[org.apache.curator.framework.imps.CuratorFrameworkImpl 0x627fd345 "org.apache.curator.framework.imps.CuratorFrameworkImpl@627fd345"] [(#object[org.apache.curator.framework.recipes.nodes.PersistentEphemeralNode 0x3f7bba75 "org.apache.curator.framework.recipes.nodes.PersistentEphemeralNode@3f7bba75"] #object[org.apache.curator.framework.recipes.nodes.PersistentEphemeralNode 0x2ff9bbb0 "org.apache.curator.framework.recipes.nodes.PersistentEphemeralNode@2ff9bbb0"]) (#object[org.apache.curator.framework.recipes.leader.LeaderSelector 0x28513142 "org.apache.curator.framework.recipes.leader.LeaderSelector@28513142"])]]
    boot.user=> (cluster/stop-slacker-server server)
    java.lang.IllegalArgumentException: No matching field found: stop for class org.apache.curator.framework.recipes.nodes.PersistentEphemeralNode

**Comment by sunng87** [comment]
Thanks! Seems there is something wrong with `stop-slacker-server`. I will look into this later.

**Comment by sunng87** [comment]
Please update to 0.12.11, this issue should be fixed now.

**Comment by mbuczko** [comment]
thanks, works perfectly now :)
